# Generated by Django 4.0.5 on 2022-06-09 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bir', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Singer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('male', 'erkak'), ('female', 'ayol'), ('other', 'boshqa')], max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('music', models.FileField(upload_to='musics', verbose_name='Music files')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bir.section')),
                ('singer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bir.singer')),
            ],
        ),
    ]
